version: '3.8'

services:
  scylla:
    image: scylladb/scylla:latest
    container_name: scylla
    ports:
      - "9042:9042"
    volumes:
      - scylla_data:/var/lib/scylla
    environment:
      - SCYLLA_CLUSTER_NAME=scylla-cluster
      - SCYLLA_SEEDS=scylla

volumes:
  scylla_data:
